spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:127.0.0.1:57235, 127.0.0.1:57238}
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}

server:
  port: 8080
